services:
  uav_hardware:
    image: uav_hardware:1.0
    container_name: uav_hardware_container
    privileged: true
    devices:
      - /dev/gpiomem:/dev/gpiomem
      - /dev/gpiochip0:/dev/gpiochip0
    stdin_open: true
    tty: true
    ipc: host
    pid: host
    network_mode: host
    restart: no
    environment:
      - ROS_LOCALHOST_ONLY=0
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
              source /ros2_ws/install/setup.bash &&
              ros2 run uav_hardware buzzer_and_led_node"
